<a href="https://colab.research.google.com/github/aamorgan/Colaboratory/blob/main/Copy_of_00_TessorFlow_fundimentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going tocover some of the most fundimental concepts of tensors using TensorFlow

More specifically, we're ghoing to cover:
  * introduction to tensors
  * Getting infoirmation from tensors
  * Manipulating tensors
  * Tensors & NumPy
  * Using @tf.function (a way to speed up you Python functions)
  * Using GPUs with TensorFlow (or TPUs)
  * Exersizes to try for myself


## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.9.2


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stand for the number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix (has more more that 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [44., 6.]], dtype=tf.float16) # specify the datatype with tf.float
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [44.,  6.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Let's create a TENSOR!!
tensor = tf.constant([[[1, 2, 3],[4, 5, 6], [7, 8, 9]],[[1, 2, 3],[4, 5, 6], [7, 8, 9]],[[1, 2, 3],[4, 5, 6], [7, 8, 9]]])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [11]:
tensor.ndim

3

### Creating Tensors with `tf.Variable`


In [12]:
changeable_variable = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_variable, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
changeable_variable[0].assign(7)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating Random Tensors
Tensors of arbitrary size with random  numbers

In [14]:
 # Create a random tensor with shape (2, 3)
random_1 = tf.random.Generator.from_seed(42)
random_1 = tf.random.normal(shape=(3, 3))
random_2 = tf.random.Generator.from_seed(42)
random_2 = tf.random.normal(shape=(3, 3))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-1.088157  ,  1.7188773 ,  1.3785589 ],
        [-1.9688269 , -0.04555538, -0.3878026 ],
        [ 0.20056592,  1.1760765 , -1.0818911 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-2.8007269e-01,  5.4455525e-01, -2.6462901e+00],
        [-1.6868650e+00, -1.0715064e+00, -1.3154598e+00],
        [-1.1376157e+00, -1.7618894e-03,  1.2774322e+00]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False],
        [False, False, False]])>)

### Shuffle the order of elements in a tensor

In [15]:
# Shuffle a tensor (valuable for when you want to shuffle you data so that there is no inherent order)
import tensorflow as tf

# Create a tensor with shape (4, 2)
original_tensor = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]])

# Shuffle the elements of the tensor
shuffled_tensor1 = tf.random.shuffle(original_tensor)

tf.random.set_seed(11) # Random but does not change
shuffled_tensor2 = tf.random.shuffle(original_tensor)
shuffled_tensor1, shuffled_tensor2

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [7, 8],
        [5, 6],
        [3, 4]], dtype=int32)>, <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [7, 8],
        [5, 6]], dtype=int32)>)

In [16]:
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [17]:
# You can turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
tensor_A = tf.constant(numpy_A, shape=(2, 3, 4))
tensor_B = tf.constant(numpy_A)
tensor_A, tensor_B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors
When dealing with tensors you probably want to be aware of the following attributes:
 * Shape
 * Rank
 * Axis or dimension
 * Size

In [18]:
#  Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [19]:
rank_4_tensor[:, :, 0]

<tf.Tensor: shape=(2, 3, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [20]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2,:2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [21]:
# the first element from each dimension from each index except for the final one 
rank_4_tensor[:1 ,:1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [22]:
# Add in extra dimension to a rank 2 tensor
rank_2_tensor = tf.constant([[10,17],
                 [21,3]])
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis] # or rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [17]],

       [[21],
        [ 3]]], dtype=int32)>

In [23]:
# Alternative to expand axis
rank_3a_tensor = tf.expand_dims(rank_2_tensor, axis=0)
rank_3a_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10, 17],
        [21,  3]]], dtype=int32)>

### Maniupulating Tensors (Tensor operations)

**Basic Operations**

`+`, `-`, `*` and `/`
 


In [24]:
tensor = tf.ones(shape = [2, 2])
(tensor + 10) * 21

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[231., 231.],
       [231., 231.]], dtype=float32)>

In [25]:
tf.math.add(tf.multiply(tensor, 10), 13)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[23., 23.],
       [23., 23.]], dtype=float32)>

**Matrix Multiplication**

In Tensor manipulation matrix manipulation is very important


In [26]:
matrix_1 = tf.constant([[1, 2, 3],
                       [4, 5, 6]])
matrix_2 = tf.constant( [[7, 8],
                        [9, 10],
                       [11, 12]])
tf.matmul(matrix_1, matrix_2), matrix_1 @ matrix_2, matrix_1 * matrix_2

InvalidArgumentError: ignored

In [27]:
import tensorflow as tf

# Create two matrices
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result = tf.matmul(a, b)

# Print the result
print(result)  # Output: [[19 22], [43 50]]


tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [32]:
tf.math.reduce_std(tf.cast(result, tf.float32)),
tf.math.reduce_variance(tf.cast(result, tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=176.25>

### Find Positional Minmum and Maximum

In [34]:
# Create a new tensor for finding positional min and max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [35]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [41]:
# Index on our largest value index, use to find value, test with reduce_max
posMax = tf.argmax(F)
posMax, F[posMax], tf.reduce_max(F), F[tf.argmax(F)]==tf.reduce_max(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>)

In [38]:
# Index on our smallest value index, use to find value, test with reduce_min
posMin = tf.argmin(F)
posMin, F[posMin], tf.reduce_min(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [44]:
# Create a new tensor to practice SQUEEZING
tf.random.set_seed(42)
# Remove all single dimensions
G = tf.random.uniform(shape=[1, 1, 2, 1, 50])
G_squeezed = tf.squeeze(G)
G, G_squeezed

(<tf.Tensor: shape=(1, 1, 2, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]],
 
          [[0.6073899 , 0.46523476, 0.97803545, 0.7223145 , 0.32347047,
            0.82577336, 0.4976915 , 0.19483674, 0.7588748 , 0.3380444 ,
            0.28128064, 0.31513572, 0.60670924, 0.7498598 , 0.5016055 ,
 

###One Hot Encoding

In [45]:
# Create a list of indicies
some_list = [0, 1, 2, 3, 4]
depth = 4
tf.one_hot(some_list, depth)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [48]:
# Custom One-Hots
tf.one_hot(some_list, depth, on_value="Yeah you bedda!", off_value="Oh, no you didn't!")

<tf.Tensor: shape=(5, 4), dtype=string, numpy=
array([[b'Yeah you bedda!', b"Oh, no you didn't!", b"Oh, no you didn't!",
        b"Oh, no you didn't!"],
       [b"Oh, no you didn't!", b'Yeah you bedda!', b"Oh, no you didn't!",
        b"Oh, no you didn't!"],
       [b"Oh, no you didn't!", b"Oh, no you didn't!", b'Yeah you bedda!',
        b"Oh, no you didn't!"],
       [b"Oh, no you didn't!", b"Oh, no you didn't!",
        b"Oh, no you didn't!", b'Yeah you bedda!'],
       [b"Oh, no you didn't!", b"Oh, no you didn't!",
        b"Oh, no you didn't!", b"Oh, no you didn't!"]], dtype=object)>

###Squaring, log and aquare root

In [49]:
H = tf.range(1, 100000)
H

<tf.Tensor: shape=(99999,), dtype=int32, numpy=array([    1,     2,     3, ..., 99997, 99998, 99999], dtype=int32)>

In [54]:
# Find the square, log and root
tf.square(H), tf.math.log(tf.cast(F, dtype=np.float16)), tf.math.sqrt(tf.cast(H, dtype=np.float16))

(<tf.Tensor: shape=(99999,), dtype=int32, numpy=
 array([         1,          4,          9, ..., 1409465417, 1409665412,
        1409865409], dtype=int32)>,
 <tf.Tensor: shape=(50,), dtype=float16, numpy=
 array([-0.4087 , -0.819  , -1.042  , -0.7666 , -3.39   , -0.379  ,
        -0.3008 , -0.1364 , -1.485  , -1.5    , -1.17   , -0.3254 ,
        -2.016  , -0.6016 , -0.5537 , -0.10547, -4.66   , -0.652  ,
        -0.4546 , -1.612  , -0.3154 , -0.6055 , -2.23   , -0.3904 ,
        -0.4153 , -1.088  , -0.5083 , -1.558  , -0.1595 , -0.8193 ,
        -0.05264, -1.4375 , -0.2083 , -0.6416 , -0.7046 , -1.531  ,
        -0.1676 , -0.1368 , -1.177  , -0.3755 , -1.437  , -0.2462 ,
        -0.03326, -2.678  , -0.2246 , -0.4153 , -0.5327 , -1.804  ,
        -0.3035 , -1.138  ], dtype=float16)>,
 <tf.Tensor: shape=(99999,), dtype=float16, numpy=array([1.   , 1.414, 1.732, ...,   inf,   inf,   inf], dtype=float16)>)