<a href="https://colab.research.google.com/github/aamorgan/Colaboratory/blob/main/Copy_of_00_TessorFlow_fundimentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going tocover some of the most fundimental concepts of tensors using TensorFlow

More specifically, we're ghoing to cover:
  * introduction to tensors
  * Getting infoirmation from tensors
  * Manipulating tensors
  * Tensors & NumPy
  * Using @tf.function (a way to speed up you Python functions)
  * Using GPUs with TensorFlow (or TPUs)
  * Exersizes to try for myself


## Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.9.2


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stand for the number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix (has more more that 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [44., 6.]], dtype=tf.float16) # specify the datatype with tf.float
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [44.,  6.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's create a TENSOR!!
tensor = tf.constant([[[1, 2, 3],[4, 5, 6], [7, 8, 9]],[[1, 2, 3],[4, 5, 6], [7, 8, 9]],[[1, 2, 3],[4, 5, 6], [7, 8, 9]]])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### Creating Tensors with `tf.Variable`


In [ ]:
changeable_variable = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_variable, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_variable[0].assign(7)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating Random Tensors
Tensors of arbitrary size with random  numbers

In [ ]:
 # Create a random tensor with shape (2, 3)
random_1 = tf.random.Generator.from_seed(42)
random_1 = tf.random.normal(shape=(3, 3))
random_2 = tf.random.Generator.from_seed(42)
random_2 = tf.random.normal(shape=(3, 3))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 1.7142028 ,  2.119748  ,  0.80830884],
        [-2.2835617 ,  1.0953517 , -0.34817252],
        [-0.5981992 , -0.22152193,  0.35625407]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.33348688, -1.1477522 , -1.5768012 ],
        [ 1.1146336 , -0.41425782, -0.8184273 ],
        [-0.5566391 ,  1.2509435 ,  1.8827959 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False],
        [False, False, False]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle you data so that there is no inherent order)
import tensorflow as tf

# Create a tensor with shape (4, 2)
original_tensor = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]])

# Shuffle the elements of the tensor
shuffled_tensor1 = tf.random.shuffle(original_tensor)

tf.random.set_seed(11) # Random but does not change
shuffled_tensor2 = tf.random.shuffle(original_tensor)
shuffled_tensor1, shuffled_tensor2

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[5, 6],
        [3, 4],
        [7, 8],
        [1, 2]], dtype=int32)>, <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [7, 8],
        [5, 6]], dtype=int32)>)

In [ ]:
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# You can turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
tensor_A = tf.constant(numpy_A, shape=(2, 3, 4))
tensor_B = tf.constant(numpy_A)
tensor_A, tensor_B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors
When dealing with tensors you probably want to be aware of the following attributes:
 * Shape
 * Rank
 * Axis or dimension
 * Size

In [ ]:
#  Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:, :, 0]

<tf.Tensor: shape=(2, 3, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2,:2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# the first element from each dimension from each index except for the final one 
rank_4_tensor[:1 ,:1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Add in extra dimension to a rank 2 tensor
rank_2_tensor = tf.constant([[10,17],
                 [21,3]])
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis] # or rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [17]],

       [[21],
        [ 3]]], dtype=int32)>

In [ ]:
# Alternative to expand axis
rank_3a_tensor = tf.expand_dims(rank_2_tensor, axis=0)
rank_3a_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10, 17],
        [21,  3]]], dtype=int32)>

### Maniupulating Tensors (Tensor operations)

**Basic Operations**

`+`, `-`, `*` and `/`
 


In [ ]:
tensor = tf.ones(shape = [2, 2])
(tensor + 10) * 21

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[231., 231.],
       [231., 231.]], dtype=float32)>

In [ ]:
tf.math.add(tf.multiply(tensor, 10), 13)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[23., 23.],
       [23., 23.]], dtype=float32)>

**Matrix Multiplication**

In Tensor manipulation matrix manipulation is very important


In [ ]:
matrix_1 = tf.constant([[1, 2, 3],
                       [4, 5, 6]])
matrix_2 = tf.constant( [[7, 8],
                        [9, 10],
                       [11, 12]])
tf.matmul(matrix_1, matrix_2), matrix_1 @ matrix_2, matrix_1 * matrix_2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[29, 32],
        [83, 92]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[29, 32],
        [83, 92]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 7, 16],
        [44, 60]], dtype=int32)>)

In [ ]:
import tensorflow as tf

# Create two matrices
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result = tf.matmul(a, b)

# Print the result
print(result)  # Output: [[19 22], [43 50]]


tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
